# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout tools repo
          uses: actions/checkout@v3
          with:
            repository: jaydattd/test-reusable
            path: test-reusable
    
        - name: call workflow    
          uses: ./test-reusable/.github/scripts/ta
