# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
        default: 'abc'
    secrets:
      envPAT:
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: print called workflow
        # env:
        #   GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo ${{ inputs.config-path }}
          echo ${{ github.workflow_ref }}
          echo ${{ github.ref }}
          # echo ${{ toJson(github) }}
          # echo "${{ toJson(github) }}"
        
      # - name: Run smoke test
      #   id: smoke_test_run
      #   uses: ./.github/scripts/actions/test
        
         
        # - name: Checkout tools repo
        #   uses: actions/checkout@v3
        #   with:
        #     repository: jaydattd/test-reusable
        #     path: test-reusable
    
        # - name: call workflow    
        #   uses: ./test-reusable/.github/scripts/ta
